### ISSUE TITLE
integrate the new look and feel (branding)

### ISSUE THREAD

**Issue by grahame** [ealgis/ealgis#41]
- [x] Sidebar empty state (faded logo?) OR no sidebar if not being used?

**Comment by keithamoss** [comment]
Dupe of #41

**Comment by keithamoss** [comment]
We've used a few random colours in the development so far. Since we've decided on purple as the primary colour via the logo let's create a proper theme for EALGIS that adheres to the material design spec and guidance.

[Material Design: Style & Colour](https://material.io/guidelines/style/color.html)
[Google's Material Colour Tool](https://material.io/color/)
[Third Party Material Palette Creator](https://www.materialpalette.com/)

Material-UI supports [custom themes](http://www.material-ui.com/#/customization/themes).

**Comment by keithamoss** [comment]
- [ ] Point all relevant uses of `/styles/colors` at muiTheme
- [ ] Base64 inline move to dev deps
- [ ] Make logo SVG
- [ ] OL colours
